mainSections = ["post","posts"]
profileImage = "/images/headshot.jpg"
dateFormat = "2 January 2023"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = false
delayDisqus = true
showRelatedPosts = false 
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "10"
