color = 'linen'                           # linen, wheat, gray, light

# header social icons
github = 'altxtech'                 # github.com/YOUR_GITHUB_ID
linkedin = 'altxtech'             # linkedin.com/in/YOUR_LINKEDIN_ID
rss = false                                # show rss icon

# home page profile
name = 'Altx Tech'
bio = 'A personal blog about Data Engineering.'

