brand = "Altx Tech"                      # name of your site - appears in the sidebar
# brand_image = "/images/headshot.jpg"    # path to the image shown in the sidebar
description = "Data Engineering" # Used as default meta description if not specified in front matter
dark_mode = false                     # optional - defaults to false
# favicon = "favicon.png"             # path to favicon (defaults to favicon.png)

# MENU PLACEHOLDER
# Menu dict keys:
	# Name:         The name to display on the menu.
	# URL:          The directory relative to the content directory.
	# HasChildren:  If the directory's files should be listed.  Default is true.
	# Limit:        If the files should be listed, how many should be shown.
menu = [
	{Name = "About", URL = "/about/", HasChildren = false},
]

# Links to your socials.  Comment or delete any you don't need/use. 
github_url = "https://github.com/altxtech"
linkedin_url = "https://www.linkedin.com/in/andré-luiz-tiago-soares-689b7314a"
email_url = "mailto://andre.soares@altxtech.net"

# NOTE: If you don't want to use RSS, comment or delete the following lines
# Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
rss_icon = false
# Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
rss_section = "posts"

# Hex colors for your content in light mode.
text_color = "#444"             # default is #222
content_bg_color = "#FAF9F6"    # default is #FAF9F6
post_title_color = "#303030"    # default is #303030
list_color = "#5a5a5a"          # default is #5a5a5a
link_color = "#268bd2"          # default is #268bd2
date_color = "#515151"          # default is #515151
table_border_color = "#E5E5E5"  # default is #E5E5E5
table_stripe_color = "#F9F9F9"  # default is #F9F9F9

# Hex colors for your content in dark mode
text_color_dark = "#eee"                # default is #eee
content_bg_color_dark = "#121212"       # default is #121212
post_title_color_dark = "#DBE2E9"       # default is #DBE2E9
list_color_dark = "#9d9d9d"             # default is #9d9d9d
link_color_dark = "#268bd2"             # default is #268bd2
date_color_dark = "#9a9a9a"             # default is #9a9a9a
table_border_color_dark = "#515151"     # default is #515151
table_stripe_color_dark = "#202020"     # default is #202020
code_color = "#bf616a"                  # default is #bf616a
code_background_color = "#E5E5E5"       # default is #E5E5E5
code_color_dark = "#ff7f7f"             # default is #ff7f7f
code_background_color_dark = "#393D47"  # default is #393D47
