baseURL = 'https://blog.altxtech.net'
languageCode = 'en-us'
title = 'Altx Blog!'
theme = 'archie'

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "dev"
# Deployed to azure
URL = "azblob://$web"
