name: CI

on:
    push:
        branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Login to azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      env:
        AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_KEY: ${{ env.AZURE_STORAGE_KEY }}
      run: hugo deploy
